import type { SupabaseClient } from '@supabase/supabase-js';

/**
 * Authoritative response synchronization.
 *
 * Shared by `POST /api/exam/save` (routine + retry flushes) and `submitExam`
 * (final pre-submission reconciliation) so exactly one implementation decides
 * how a response operation is applied.
 *
 * Idempotency contract:
 *   - every operation carries an `operationId` (uuid) generated by the client
 *     when the answer was saved locally;
 *   - the server stores it in `student_responses.last_operation_id`;
 *   - a retried operation whose id already matches is ACKNOWLEDGED WITHOUT
 *     being applied again (lost-ack retry ⇒ exactly one logical update);
 *   - a stale operation (`clientRevision < server_revision`) is not applied —
 *     the server state wins (protects against out-of-order replays), and the
 *     caller is told so it can reconcile;
 *   - once the attempt is no longer `in_progress`, nothing is applied.
 *
 * Validation performed here (after the caller has verified ownership):
 *   - question must be part of the attempt manifest (never the whole pool);
 *   - selected choice must belong to that question;
 *   - payload shapes are re-validated — the queue can replay stale data.
 */

export interface SyncOperation {
  operationId: string | null;
  questionId: string;
  selectedChoiceId: string | null;
  textAnswer: string | null;
  clientRevision: number;
}

export interface ApplyOperationsResult {
  /** questionId -> server revision after processing (applied, duplicate or stale). */
  serverRevisions: Record<string, number>;
  /** Questions actually mutated. */
  applied: string[];
  /** Questions acknowledged without applying (already-applied retry). */
  duplicates: string[];
  /** Questions refused (stale revision or invalid payload). */
  rejected: string[];
}

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const MAX_TEXT_ANSWER_LENGTH = 10_000;

function isUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID_RE.test(value);
}

export function normalizeOperation(
  raw: unknown
): SyncOperation | null {
  if (!raw || typeof raw !== 'object') return null;
  const op = raw as Record<string, unknown>;

  if (!isUuid(op.questionId)) return null;
  if (op.selectedChoiceId !== null && !isUuid(op.selectedChoiceId)) return null;
  if (op.textAnswer !== null && typeof op.textAnswer !== 'string') return null;
  if (typeof op.textAnswer === 'string' && op.textAnswer.length > MAX_TEXT_ANSWER_LENGTH) {
    return null;
  }
  if (op.operationId !== null && op.operationId !== undefined && !isUuid(op.operationId)) {
    return null;
  }

  const clientRevision = Number(op.clientRevision);
  if (!Number.isFinite(clientRevision) || clientRevision < 0) return null;

  return {
    operationId: typeof op.operationId === 'string' ? op.operationId : null,
    questionId: op.questionId,
    selectedChoiceId: (op.selectedChoiceId as string | null) ?? null,
    textAnswer: (op.textAnswer as string | null) ?? null,
    clientRevision: Math.floor(clientRevision),
  };
}

export async function applyResponseOperations(
  admin: SupabaseClient,
  attemptId: string,
  operations: SyncOperation[]
): Promise<ApplyOperationsResult> {
  const result: ApplyOperationsResult = {
    serverRevisions: {},
    applied: [],
    duplicates: [],
    rejected: [],
  };

  if (operations.length === 0) return result;

  // 1. Attempt must still be open for business.
  const { data: attempt } = await admin
    .from('exam_attempts')
    .select('id, status')
    .eq('id', attemptId)
    .maybeSingle();

  if (!attempt || attempt.status !== 'in_progress') {
    for (const op of operations) result.rejected.push(op.questionId);
    return result;
  }

  // 2. Manifest: only the questions this attempt actually contains.
  const { data: manifest } = await admin
    .from('exam_manifests')
    .select('question_order')
    .eq('attempt_id', attemptId)
    .maybeSingle();

  const manifestIds = new Set<string>((manifest?.question_order as string[]) ?? []);

  const questionIds = [
    ...new Set(operations.map((op) => op.questionId).filter((id) => manifestIds.has(id))),
  ];
  if (questionIds.length === 0) {
    for (const op of operations) result.rejected.push(op.questionId);
    return result;
  }

  // 3. Choice membership: the selected choice must belong to its question.
  const { data: choiceRows } = await admin
    .from('question_choices')
    .select('id, question_id')
    .in('question_id', questionIds);

  const choicesByQuestion = new Map<string, Set<string>>();
  for (const row of choiceRows ?? []) {
    const set = choicesByQuestion.get(row.question_id) ?? new Set<string>();
    set.add(row.id);
    choicesByQuestion.set(row.question_id, set);
  }

  // 4. Current server state for all involved questions (single read).
  const { data: existingRows } = await admin
    .from('student_responses')
    .select('id, question_id, server_revision, last_operation_id')
    .eq('attempt_id', attemptId)
    .in('question_id', questionIds);

  const existingByQuestion = new Map(
    (existingRows ?? []).map((row) => [row.question_id, row])
  );

  const nowIso = new Date().toISOString();

  for (const op of operations) {
    if (!manifestIds.has(op.questionId)) {
      result.rejected.push(op.questionId);
      continue;
    }

    if (op.selectedChoiceId !== null) {
      const allowed = choicesByQuestion.get(op.questionId);
      if (!allowed || !allowed.has(op.selectedChoiceId)) {
        result.rejected.push(op.questionId);
        continue;
      }
    }

    const existing = existingByQuestion.get(op.questionId);

    // Idempotent retry: the server already applied this exact operation.
    if (existing && op.operationId && existing.last_operation_id === op.operationId) {
      result.serverRevisions[op.questionId] = existing.server_revision;
      result.duplicates.push(op.questionId);
      continue;
    }

    // Stale/out-of-order: server state wins (no blind last-write-wins).
    if (existing && op.clientRevision < existing.server_revision) {
      result.serverRevisions[op.questionId] = existing.server_revision;
      result.rejected.push(op.questionId);
      continue;
    }

    if (existing) {
      const { data: updated, error } = await admin
        .from('student_responses')
        .update({
          selected_choice_id: op.selectedChoiceId,
          text_answer: op.textAnswer,
          client_revision: op.clientRevision,
          server_revision: existing.server_revision + 1,
          last_operation_id: op.operationId,
          updated_at: nowIso,
        })
        .eq('id', existing.id)
        .eq('server_revision', existing.server_revision) // optimistic guard
        .select('server_revision')
        .single();

      if (error || !updated) {
        // Concurrent writer won the row — report the authoritative revision.
        const { data: fresh } = await admin
          .from('student_responses')
          .select('server_revision')
          .eq('id', existing.id)
          .single();
        result.serverRevisions[op.questionId] = fresh?.server_revision ?? existing.server_revision;
        result.rejected.push(op.questionId);
        continue;
      }

      result.serverRevisions[op.questionId] = updated.server_revision;
      result.applied.push(op.questionId);
      existingByQuestion.set(op.questionId, {
        id: existing.id,
        question_id: op.questionId,
        server_revision: updated.server_revision,
        last_operation_id: op.operationId,
      });
    } else {
      const { data: created, error } = await admin
        .from('student_responses')
        .insert({
          attempt_id: attemptId,
          question_id: op.questionId,
          selected_choice_id: op.selectedChoiceId,
          text_answer: op.textAnswer,
          client_revision: op.clientRevision,
          server_revision: 1,
          last_operation_id: op.operationId,
        })
        .select('server_revision')
        .single();

      if (error || !created) {
        result.rejected.push(op.questionId);
        continue;
      }

      result.serverRevisions[op.questionId] = created.server_revision;
      result.applied.push(op.questionId);
    }
  }

  return result;
}
